### ISSUE TITLE
Automate-Click

### ISSUE THREAD

**Issue by astranberg** [igorlogius/igorlogius#1]
Hello,

What happened to the firefox plugin automate-click? I see it's been taken down.

Any chance you'd share the file with me? My wife depended on it to automate clicking of grocery store coupons.

Thanks,
Adam

**Comment by igorlogius** [comment]
> What happened to the firefox plugin automate-click? 

I've taken it down from AMO and stored it onto my archive repository: https://github.com/igorlogius/not-on-amo/ . The reason being that i found/discovered an alternative addon [automa](https://addons.mozilla.org/en-US/firefox/addon/automa/) that was just so much better in every aspect that it seemed unnecessary to continue to maintain/distribute AC further.    

> Any chance you'd share the file with me?

Sure, if you still want to continue using AC, you can download the signed XPI here: 
https://github.com/igorlogius/not-on-amo/blob/main/automate_click-1.14.7.xpi 
and manually install it.

In the long term, i'd still suggest to migrate to [automa](https://addons.mozilla.org/en-US/firefox/addon/automa/), but AC should continue to work for quite a while, so no rush. i'll even continue to fix bugs but wont be adding any new features, since automa already seems to have everything covered.
