### ISSUE TITLE
[Open in Temp Container] Context menu item active on plain text selections

### ISSUE THREAD

**Issue by anewuser** [igorlogius/igorlogius#11]
1. Select some plain text
2. Right-click

"Open in Temp Container" shouldn't be in this menu:

![bug](https://github.com/igorlogius/igorlogius/assets/6733770/12216ece-b450-4204-b628-27c81bf257d5)

Firefox 125.0.1
Windows 10

**Comment by igorlogius** [comment]
This is a sideeffect from adding the function to open multilple links in selections. 

Fixing this would require to always analyse the selection and update the context menu when there are no links found in the selections. 

Since updating the menu adds a little more code and can cause some flickering, i did not go that route and just always displayed the context menu, but i see how this might cause some confusion. 

I'll have to test and see if i can implemented it in a way that doest not cause any visual issues.

**Comment by anewuser** [comment]
It's better to leave it as it is then. I've hidden it with CSS: https://github.com/anewuser/firefox-clean-dark-theme/commit/2655b381608a6fa8c3ab797c252b31a82332a073 .

You can also force the context menu option to be at the bottom when you click on links:

    #contentAreaContextMenu menuitem[label^="Open in Temp Container"]{order:99!important;}
