### ISSUE TITLE
[auto-close-tabs] not closing when tabs are unloaded/discarded

### ISSUE THREAD

**Issue by cecton** [igorlogius/igorlogius#13]
**Steps to Reproduce**

I have opened an issue recently because Auto Close Tabs wasn't working for me. You did fix something. :heart: I thought I had to wait another cycle (15 days) before it starts working but it seems it still does not work on my side. When I enable it, nothing happens.

**Expected result**

Tabs to be closed and saved to bookmarks.

**Actual result**

Nothing.

**Screenshots**

![screenshot2](https://github.com/igorlogius/igorlogius/assets/3018448/4e0067bd-4c17-4e7f-8a0b-7fdd49e6bd1a)

**Other additional information**

(I just watched the demo and I was wondering at which interval you do this timer. I start and stop my computer every day so maybe my browser is not active when the scheduler actually hits? It's just a wild guess I don't do JS or browser extensions.)

**Comment by igorlogius** [comment]
Are you using some tab suspension addon or are the tabs unloaded after restarting the browser?

**Comment by igorlogius** [comment]
i pushed a new version with a "workaround" that i hope will help with the issue.

At its core one of the addon api function `browser.tabs.executeScript` silently failed without throwing an error, when it was used against an unloaded tab. This caused the tabs to always stay ope, because the closing function could never be reached.  

Since this behaviour is AFAIK not documented and i'd say we found ourself a browser bug.

Anyway, please check out the new version and see if it now behaves as you'd expect.

**Comment by cecton** [comment]
Yes!! It worked this time, thanks a lot!
