### ISSUE TITLE
[Open in Temp Container] Keep "Special Options" visible

### ISSUE THREAD

**Issue by anewuser** [igorlogius/igorlogius#19]
### Steps to Reproduce

1. Click on the tiny "Special Options" button 
2. Enter a URL
3. Click on `Add`

### Expected Result

This section should remain permanently visible unless the user decides to hide it again.

### Actual Result

The entire "Special Options" section is hidden as soon as you add a regex.

Also, all it takes to add a regex is pressing `Add`, but to remove it, you have to press `Delete`  _and then_ `Save`. Maybe you could add an asterisk to `Save`  to indicate that there are unsaved changes.

### Additional Information

Open in Temp Container 1.1.31
Firefox 126.0

**Comment by igorlogius** [comment]
Yeah, the none peristent state of the special options visibility is annyoing.

> you have to press Delete and then Save

that is/was intentional ... kind of like a confirmation so a user would not accidentally remove something. 

I might rework the area and just make it into a textarea, which each line interpreted as a regex ... that way i dont need  to rebuild the table ...

**Comment by igorlogius** [comment]
should be fixed in `1.1.32`
