### ISSUE TITLE
[Export Bookmarks as Text] .part output files

### ISSUE THREAD

**Issue by andreyjc** [igorlogius/igorlogius#20]
### Question

Why is my output file random alphanumeric characters followed by ".txt" and ending in ".part"?

**Comment by igorlogius** [comment]
Hello. Nice of you to get in contact, i'll see what i can do to help out. 

Are you refering to any specific addon? 
I'll just assume you mean one that saves/downloads something.

`.part` files are AFAIK a normal part of firefox download process, but those should be renamed after the download has finished.  If that doesnt happend, then usually that indicates some kind of issue with your system or browser profile. 

Do the files still contain the expected data? 

I got report of a similar sounding issue in the past and it turns out that it was unrelated to any addon behaviour. see https://github.com/igorlogius/igorlogius/issues/10

**Comment by andreyjc** [comment]
The FF add-on is Export Bookmarks as Text and it seems the .part file contains the expected data. If it is not the add-on but just my system then fine.

Thank you.

**Comment by igorlogius** [comment]
When i test with an unmodfied second profile i dont see any issue.

[demo-2024-05-19_21.28.29.webm](https://github.com/igorlogius/igorlogius/assets/67047467/16f666e3-ee91-41e8-bef2-cee262b4eb3f)

If the behaviour on your side is the same i'd say we can assume that the issue is not with the addon.

Hope this info helps.
