### ISSUE TITLE
[auto-close-tabs]  "Autostart" option function unclear

### ISSUE THREAD

**Issue by raddevon** [igorlogius/igorlogius#22]
### Question

That's it. Not clear what the "Autostart" option does.

Thank you! Looking forward to using this add-on!

**Comment by raddevon** [comment]
I may have just answered my own question. I noticed that, when I ticked the box, the flag on the toolbar icon flipped from "off" to "on." I'm assuming "autostart" actually enables the automatic closing functionality.

Could I suggest renaming this to "active" or "enabled" to clarify the functionality? Unless there is a manual trigger option that I'm not aware of, "autostart" is a bit more ambiguous in this context.

**Comment by igorlogius** [comment]
>  I'm assuming "autostart" actually enables the automatic closing functionality.

Not exactly, normally, when you startup your browser the addon is in a disabled state and you manually need to klick the toolbar button to enable the cleanup cycle for each window.

Now the "Autostart" option was added for people why want the addon be enabled from the start and for all newly created windows, instead of having to manually enable it. 

But yeah, it might be a good idea to add some explaination

**Comment by igorlogius** [comment]
Help icon added to version in new version.
