### ISSUE TITLE
What happened to the Automate Click extension

### ISSUE THREAD

**Issue by J4gQBqqR** [igorlogius/igorlogius#32]
### Question

Hi, could you provide a little bit information why the extension is delisted? I found it very useful and was using it a lot. Thank you.

**Comment by igorlogius** [comment]
Sure, i can elaborate. It's not really a secret or anything. 

The main reason it took the addon down, was because i found out there is an far more feature complete alternative called [automa](https://addons.mozilla.org/en-US/firefox/addon/automa/)
After finding it i just did not have the motivation to continue actively developing automate-click, since automa already covered every imaginable usecase and more.  

If you still want to use automate-click, you can download the last signed xpi from [here](https://github.com/igorlogius/unlisted) and install it manually. - I think it should still work, since AFAIK, there weren't any API changes that should have broken it. 

If you do decide to use it, i'd just like to note, that i will not be adding any features, but you can still report bugs, in which case i'll try to release a patch version.

Hope that clears things up and sorry for the trouble.

**Comment by igorlogius** [comment]
Maybe i should re-upload the addon to AMO and just mark it as in "maintainace mode" ...
