### ISSUE TITLE
[Copy Link Extras]: Keyboard Shortcut 

### ISSUE THREAD

**Issue by cy-james-lee** [igorlogius/igorlogius#53]
### Description

It would be great to be able to have the option of binding custom keyboard shortcuts like Bitwarden shown here:
![image](https://github.com/user-attachments/assets/8e2a5671-43f5-4ec7-96dd-616bd7dfaa1d)

**Comment by igorlogius** [comment]
Hi :wave: 

Thanks for taking the open this issue.

I suspect you mean you'd like to be able to hover over a link and use a shortcut to active a  copy action.

While that is doable it would require the very broad "Access all data on all websites" permission,  because there is ATM no other way to get the hovered link information.  

While i agree that adding this functionality would be a boost in productivity, i fear that the permission will scare users away from trying the addon. 


But ... , i might be able to make the permission "optional" in that case the additional shortcut functionality could be enabled/disabled by the users. I think that might be doable, but i'll have to look into that.


Hope i understood you correctly, if not, let me know.

**Comment by cy-james-lee** [comment]
Hello @igorlogius, do you need the "Access all data on all website" permission for hover over functionality? Because that's not my use case. I just use simple select a bunch of stuff and then copy text + url like this:
![image](https://github.com/user-attachments/assets/ca4b3759-7bda-4321-9566-405bc8c523ee)

If I could bind it to something like Ctrl+Alt+C, it would be so much better.

**Comment by igorlogius** [comment]
That text selection case ... might be handable without the broad permission. 
I'll check what i can do.

**Comment by igorlogius** [comment]
Seems to work, i'll push a new version where you can set shortcuts for the first five copy actions. 

![image](https://github.com/user-attachments/assets/830dac7f-06d8-4f1a-804f-94651a44301f)

**Comment by igorlogius** [comment]
version is available on AMO. 

Have fun, and let me know if something isn't working or if you have any other kind of feedback.
