### ISSUE TITLE
[Save Website as Image]: Option to save as specific image format

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [igorlogius/igorlogius#54]
### Description

The Save Website as Image extension currently support JPEG format only, but it would be nice to have an option to specify other image format as PNG, WebP, or JXL.

**Comment by igorlogius** [comment]
Hi, thanks for taking the time to make this suggestion.

i could add a png output options, but webP and jXL would require adding image conversion libraries which i rather not intorduce into the codebase.

I am also a bit unsure if such an option would really be that much of a benefit, since i always felt that people who require a specific format very few and are likely already able to convert the jpg image if necessary.

**Comment by KrasnayaPloshchad** [comment]
OK I think you can provide an option for PNG first. For other formats, you can think of submitting a request for corresponding APIs at bugzilla.mozilla.org and then waiting for their fixes.

**Comment by igorlogius** [comment]
I added the png output option to `1.4.24`

in regards to the webP, i personally do not like this format and wont make any effort in adding it as an output option, unless a strong request for it is made by the userbase.

jXL i'd like to add, but i'll wait until mozillas rust based encoder+decoder is built-in, then i'll see if i can somehow interface with it. If not, i might open a request for it then.
